# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20170410_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='all', max_length=128),
        ),
    ]
